version: "3"

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - monitoring

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: always
    environment:
      - ZBX_HOSTNAME=flask-app
      - ZBX_SERVER_HOST=192.168.217.128
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge